#!/usr/bin/env python3
"""Render a monospace TrueType face into a fixed-cell bitmap font as a C table.

    tools/gen-font.py /usr/share/fonts/truetype/dejavu/DejaVuSansMono.ttf 15 ui \
        > platform/tg_font_ui.c

The RetailOS raw surface has no text rendering at all, so TinyGB carries its
own: ASCII 32..126, one fixed cell per glyph, one bit per pixel. The output is
committed, so a build never needs Pillow or the face; this script is how the
table was made and how it gets remade at another size.

DejaVu Sans Mono is under the Bitstream Vera licence, which permits exactly
this: bitmaps derived from it, shipped inside a program.
"""
import sys
from PIL import Image, ImageDraw, ImageFont

if len(sys.argv) != 4:
    sys.exit(__doc__)

path, px, name = sys.argv[1], int(sys.argv[2]), sys.argv[3]
font = ImageFont.truetype(path, px)
ascent, descent = font.getmetrics()
cell_h = ascent + descent
cell_w = int(round(font.getlength("M")))
if cell_w > 16:
    sys.exit("cell wider than 16 px does not fit a uint16 row")

first, last = 32, 126
rows = []
for code in range(first, last + 1):
    im = Image.new("L", (cell_w, cell_h), 0)
    ImageDraw.Draw(im).text((0, 0), chr(code), font=font, fill=255)
    for y in range(cell_h):
        bits = 0
        for x in range(cell_w):
            if im.getpixel((x, y)) >= 128:
                bits |= 1 << x          # bit 0 is the leftmost pixel
        rows.append(bits)

out = sys.stdout
out.write("/* Generated by tools/gen-font.py from %s at %d px. Do not edit. */\n"
          % (path.rsplit("/", 1)[-1], px))
out.write('#include "tg_text.h"\n\n')
out.write("static const uint16_t k_rows[%d] = {\n" % len(rows))
for code in range(first, last + 1):
    i = (code - first) * cell_h
    chunk = rows[i:i + cell_h]
    out.write("    /* %3d %s */ %s,\n" % (code, "'%s'" % chr(code) if code != 92 else "'\\\\'",
                                         ", ".join("0x%04X" % r for r in chunk)))
out.write("};\n\n")
out.write("const tg_font tg_font_%s = { %d, %d, %d, %d, k_rows };\n"
          % (name, cell_w, cell_h, first, last - first + 1))
sys.stderr.write("%s: cell %dx%d, %d glyphs, %d bytes\n"
                 % (name, cell_w, cell_h, last - first + 1, len(rows) * 2))
